version: "3.7"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    networks:
      - smarthome-backend

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "8080:8080"
#    networks:
#      - smarthome-backend

  mosquitto:
    image: eclipse-mosquitto:1.6.9
    ports:
      - "1883:1883"
    networks:
      - smarthome-backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - "db"
    restart: always
    ports:
      - "8088:80"
    volumes:
      - /sessions
    networks:
      - smarthome-backend

networks:
  smarthome-backend:

