server:
  port: 8090

smartHome:
  mqtt:
    server:
      address: localhost
      port: 1883
    devices:
      sensor:
        topic: "nodemcu_sensor/measurements"
      lightsActuator:
        topic: "nodemcu_actuator/lights"
      heaterActuator:
        topic: "nodemcu_actuator/heat"
      coolerActuator:
        topic: "nodemcu_actuator/cool"
    enableMessageGenerator: false
  database:
    enableMeasurementsGenerator: true

spring:
  application:
    name: smarthome-backend
  jpa:
    generate-ddl: true
#    hibernate.hbm-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/smarthome
    username: root
    password: example
  security:
    user:
      name: admin
      password: admin